server:
  port: 8989
  context-path: /cmfz

  jsp-servlet:
    init-parameters:
      development: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      force: true
      charset: UTF-8
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:/com/baizhi/mapper/*.xml


